#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$1" == "-?" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Deletes PadoGrid deployment

SYNOPSIS
   $EXECUTABLE [-all] [-?]

DESCRIPTION
   Deletes PadoGrid deployment pods. If '-all' is specified then it also deletes the persistent
   claim and the 'local-storage' storage class.

OPTIONS
   -all
             If specified then it also deletes the 'padogrid-pvc' persistent claim along with
             'local-storage'.

EOF
exit
fi

HAZELCAST_ENTERPRISE_SERVICES="$(kubectl get svc | grep hazelcast-enterprise)"

if [ "$HAZELCAST_ENTERPRISE_SERVICES" != "" ]; then
  CONFIGMAP_FILE="padogrid-configmap-enterprise.yaml"
else
  CONFIGMAP_FILE="padogrid-configmap-oss.yaml"
fi

echo "Deleting PadoGrid..."
kubectl delete -f $APP_DIR/padogrid/$CONFIGMAP_FILE
kubectl delete -f $APP_DIR/padogrid/padogrid.yaml
