apiVersion: hazelcast.com/v1alpha1
kind: ManagementCenter
metadata:
  name: managementcenter-enterprise
spec:
  repository: 'hazelcast/management-center'
  version: '5.4.0'
  licenseKeySecretName: hazelcast-license-key
  externalConnectivity:
    type: LoadBalancer
  hazelcastClusters:
  - address: hazelcast-enterprise
    name: dev
